// src/ui/MarkdownRenderer.svelte
<script lang="ts">
	import { MarkdownRenderer } from "obsidian";
	import { onMount } from "svelte";
	import { contentStore } from "./ContentStore";
	import { writable } from "svelte/store";

	export let eventId: string;
	let content: string;
	$: content;

	let clazz: string | undefined = undefined;
	export { clazz as class };

	let containerEl: HTMLDivElement;

	async function renderMarkdown() {
		if (!containerEl) return; 
		containerEl.innerHTML = "";

		await MarkdownRenderer.renderMarkdown(content, containerEl, "", null);

		if (containerEl.childElementCount > 1) {
			return;
		}
		const markdownContent = containerEl.querySelector("p");
		if (markdownContent) {
			markdownContent.parentElement.removeChild(markdownContent);
			containerEl.innerHTML = markdownContent.innerHTML;
		}
	}

	onMount(async () => {
		if (
			!contentStore.has(eventId) ||
			contentStore.get(eventId) == undefined ||
			contentStore.get(eventId!) == null
		) {
			contentStore.set(eventId, writable("None"));
		}
		let ct = contentStore.get(eventId);
		if (ct !== undefined) {
			ct.subscribe(async (value) => {
				content = value;
				await renderMarkdown();
			});
		}
	});
</script>

<div bind:this={containerEl} class={clazz} />

// src/ui/MarkdownRenderer.tsx
import React, { useEffect, useRef, useState } from "react";
import {
	MarkdownRenderer as ObsidianMarkdownRenderer,
	Component,
} from "obsidian";
import { contentStore } from "./ContentStore";

interface MarkdownRendererProps {
	eventId: string;
	className?: string;
}

const MarkdownRenderer: React.FC<MarkdownRendererProps> = ({
	eventId,
	className,
}) => {
	const containerRef = useRef<HTMLDivElement>(null);
	const [content, setContent] = useState<string>("None");

	useEffect(() => {
		const renderMarkdown = async () => {
			if (!containerRef.current) return;
			containerRef.current.innerHTML = "";

			await ObsidianMarkdownRenderer.renderMarkdown(
				content,
				containerRef.current,
				"",
				new Component()
			);

			if (containerRef.current.childElementCount > 1) {
				return;
			}
			const markdownContent = containerRef.current.querySelector("p");
			if (markdownContent) {
				markdownContent.parentElement?.removeChild(markdownContent);
				containerRef.current.innerHTML = markdownContent.innerHTML;
			}
		};

		renderMarkdown();
	}, [content]);

	useEffect(() => {
		if (!contentStore.has(eventId)) {
			contentStore.set(eventId, "None");
		}
		const newContent = contentStore.get(eventId);
		if (newContent) {
			setContent(newContent);
		}
	}, [eventId]);

	return <div ref={containerRef} className={className} />;
};

export default MarkdownRenderer;
